function psi_dot = symbolic_lie_derivative(in1,u,in3)
%SYMBOLIC_LIE_DERIVATIVE
%    PSI_DOT = SYMBOLIC_LIE_DERIVATIVE(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Nov-2024 21:23:29

d = in3(:,4);
g = in3(:,2);
l = in3(:,3);
m = in3(:,1);
q = in1(1,:);
qdot = in1(2,:);
t2 = cos(q);
t3 = sin(q);
t4 = qdot.^2;
t5 = qdot.^3;
t8 = 1.0./l;
t10 = 1.0./m;
t6 = t4.^2;
t7 = t3.^2;
t9 = t8.^2;
mt1 = [qdot;-g.*t3.*t8+t9.*t10.*u-d.*qdot.*t9.*t10;qdot.*t2;-qdot.*t3;t2.*t4-g.*t7.*t8+t3.*t9.*t10.*u-d.*qdot.*t3.*t9.*t10;-t3.*t4-g.*t2.*t3.*t8+t2.*t9.*t10.*u-d.*qdot.*t2.*t9.*t10;t2.*t5-g.*qdot.*t7.*t8.*2.0-d.*t3.*t4.*t9.*t10.*2.0+qdot.*t3.*t9.*t10.*u.*2.0;-t3.*t5-d.*t2.*t4.*t9.*t10.*2.0-g.*qdot.*t2.*t3.*t8.*2.0+qdot.*t2.*t9.*t10.*u.*2.0;t2.*t6-g.*t4.*t7.*t8.*3.0-d.*t3.*t5.*t9.*t10.*3.0+t3.*t4.*t9.*t10.*u.*3.0;-t3.*t6-d.*t2.*t5.*t9.*t10.*3.0-g.*t2.*t3.*t4.*t8.*3.0+t2.*t4.*t9.*t10.*u.*3.0];
mt2 = [d.*t4.*t9.*t10.*-2.0-g.*qdot.*t3.*t8.*2.0+qdot.*t9.*t10.*u.*2.0;d.*t5.*t9.*t10.*-3.0-g.*t3.*t4.*t8.*3.0+t4.*t9.*t10.*u.*3.0];
psi_dot = [mt1;mt2];
end
